name: Auto Assign PR Creator

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    permissions:
      contents: read
      pull-requests: write
    uses: ut-issl/se-team-hub/.github/workflows/auto-assign-pr-creator.yml@main
