name: Set Iteration on Close

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  set-iteration:
    permissions: {}
    uses: ut-issl/se-team-hub/.github/workflows/set-iteration-on-close.yml@main
    secrets:
      ITERATION_AUTOMATION_APP_ID: ${{ secrets.ITERATION_AUTOMATION_APP_ID }}
      ITERATION_AUTOMATION_APP_PRIVATE_KEY: ${{ secrets.ITERATION_AUTOMATION_APP_PRIVATE_KEY }}
