name: Manage Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:

  label-pr:
    name: Label PR
    if: github.event.action != 'edited'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels/labeler.yaml
          sync-labels: false
          dot: true

  lint-pr-title:
    name: Lint PR title
    if: github.event.action != 'edited' || github.event.changes.title != null
    runs-on: ubuntu-latest

    steps:
      - name: Set up Commitizen
        uses: commitizen-tools/setup-cz@96c75e6ae9632047f2c9b4025b9dd1624b40de8f # v0.9.1
        with:
          python-version: '3.x'
          version: '4.16.2'

      - name: Lint pull request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: cz check --message "$PR_TITLE"
