name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync-labels.yaml'
      - '.github/labels/labels.yaml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/sync-labels.yaml'
      - '.github/labels/labels.yaml'

jobs:

  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels/labels.yaml
          skip-delete: false
          dry-run: ${{ github.event_name == 'pull_request' }}
